module.exports = [
  {
    date: "March 9",
    transDesc: "Dinner",
    detailDesc: "Dinner with Wife",
    onlineTrans: true,
    amount: 100,
  },
  {
    date: "March 18",
    transDesc: "Concert",
    detailDesc: "Alicia Keys Concert",
    onlineTrans: true,
    amount: 80,
  },
  {
    date: "April 27",
    transDesc: "Ice cream",
    detailDesc: "Bought ice cream at Cold stone Creamery",
    onlineTrans: false,
    amount: 20,
  },
  {
    date: "May 14",
    transDesc: "Uber",
    detailDesc: "Visited Stacy",
    onlineTrans: true,
    amount: 25,
  },
  {
    date: "May 23",
    transDesc: "Bought Computer",
    detailDesc: "Equipment Upgrade",
    onlineTrans: false,
    amount: 75,
  },
  {
    date: "May 29",
    transDesc: "Date Night",
    detailDesc: "Date night with wife",
    onlineTrans: false,
    amount: 80,
  },
  {
    date: "June 19",
    transDesc: "Parade",
    detailDesc: "Celebrated Juneteenth with friends at a parade",
    onlineTrans: false,
    amount: 40,
  },
  {
    date: "June 22",
    transDesc: "Groceries",
    detailDesc: "Groceries for the week were on me",
    onlineTrans: false,
    amount: 150,
  },
  {
    date: "June 27",
    transDesc: "New Bike",
    detailDesc: "New bicycle for daily commute",
    onlineTrans: false,
    amount: 50,
  },
  {
    date: "June 30",
    transDesc: "Movies",
    detailDesc: "Theater popcorn is expensive",
    onlineTrans: false,
    amount: 30,
  },
  {
    date: "July 4",
    transDesc: "Fireworks",
    detailDesc: "donated to community fireworks show",
    onlineTrans: true,
    amount: 25,
  },
  {
    date: "July 8",
    transDesc: "Groceries",
    detailDesc: "My turn again, for weekly groceries",
    onlineTrans: false,
    amount: 125,
  },
  {
    date: "July 18",
    transDesc: "GoFund Me",
    detailDesc: "Donated to friends GoFund me",
    onlineTrans: true,
    amount: 30,
  },
  {
    date: "July 27",
    transDesc: "Amazon",
    detailDesc: "Amazon is expensive",
    onlineTrans: true,
    amount: 50,
  },
  {
    date: "August 1",
    transDesc: "Vet",
    detailDesc: "Vets are expensive",
    onlineTrans: false,
    amount: 120,
  },
  {
    date: "August 5",
    transDesc: "Petco",
    detailDesc: "Petco food for Rex",
    onlineTrans: true,
    amount: 40,
  },
];